[test]
levels = ["syntax", "coverage", "install", "registration", "instantiation", "execution"]
publish = true

[test.workflows]
timeout = 300
cpu = [
    "!fill_holes_all",
    "!remeshing_all",
    "!uv_unwrap_all",
]
gpu = [
    "fill_holes_all",
    "remeshing_all",
    "uv_unwrap_all",
]

[test.platforms]
platforms = ["linux", "macos", "windows", "windows_portable", "macos_desktop", "windows_desktop"]