# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2025 ComfyUI-GeometryPack Contributors
"""Field transfer / interpolation nodes."""

from .interpolate_field import (
    NODE_CLASS_MAPPINGS as INTERP_MAPS,
    NODE_DISPLAY_NAME_MAPPINGS as INTERP_DISP,
)
from .edge_split import (
    NODE_CLASS_MAPPINGS as SPLIT_MAPS,
    NODE_DISPLAY_NAME_MAPPINGS as SPLIT_DISP,
)
from .backends.interpolate_field_barycentric import NODE_CLASS_MAPPINGS as IF_BARY_MAPS, NODE_DISPLAY_NAME_MAPPINGS as IF_BARY_DISP
from .backends.interpolate_field_nearest import NODE_CLASS_MAPPINGS as IF_NEAR_MAPS, NODE_DISPLAY_NAME_MAPPINGS as IF_NEAR_DISP
from .backends.interpolate_field_idw import NODE_CLASS_MAPPINGS as IF_IDW_MAPS, NODE_DISPLAY_NAME_MAPPINGS as IF_IDW_DISP
from .backends.interpolate_field_rbf import NODE_CLASS_MAPPINGS as IF_RBF_MAPS, NODE_DISPLAY_NAME_MAPPINGS as IF_RBF_DISP
from .backends.interpolate_field_gaussian import NODE_CLASS_MAPPINGS as IF_GAUSS_MAPS, NODE_DISPLAY_NAME_MAPPINGS as IF_GAUSS_DISP

NODE_CLASS_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS = {}
NODE_CLASS_MAPPINGS.update(INTERP_MAPS)
NODE_DISPLAY_NAME_MAPPINGS.update(INTERP_DISP)
NODE_CLASS_MAPPINGS.update(SPLIT_MAPS)
NODE_DISPLAY_NAME_MAPPINGS.update(SPLIT_DISP)
NODE_CLASS_MAPPINGS.update(IF_BARY_MAPS)
NODE_DISPLAY_NAME_MAPPINGS.update(IF_BARY_DISP)
NODE_CLASS_MAPPINGS.update(IF_NEAR_MAPS)
NODE_DISPLAY_NAME_MAPPINGS.update(IF_NEAR_DISP)
NODE_CLASS_MAPPINGS.update(IF_IDW_MAPS)
NODE_DISPLAY_NAME_MAPPINGS.update(IF_IDW_DISP)
NODE_CLASS_MAPPINGS.update(IF_RBF_MAPS)
NODE_DISPLAY_NAME_MAPPINGS.update(IF_RBF_DISP)
NODE_CLASS_MAPPINGS.update(IF_GAUSS_MAPS)
NODE_DISPLAY_NAME_MAPPINGS.update(IF_GAUSS_DISP)

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
