# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2025 ComfyUI-GeometryPack Contributors

"""
Texture remeshing nodes (main dependencies only - no Blender)
"""

from .texture_to_geometry import NODE_CLASS_MAPPINGS as TEXTURE_TO_GEOM_MAPS, NODE_DISPLAY_NAME_MAPPINGS as TEXTURE_TO_GEOM_DISP
from .depth_normals_to_mesh import NODE_CLASS_MAPPINGS as DEPTH_NORMALS_MAPS, NODE_DISPLAY_NAME_MAPPINGS as DEPTH_NORMALS_DISP
from .normals_to_surface import NODE_CLASS_MAPPINGS as NORM_SURF_MAPS, NODE_DISPLAY_NAME_MAPPINGS as NORM_SURF_DISP
from .rebake_texture import NODE_CLASS_MAPPINGS as REBAKE_MAPS, NODE_DISPLAY_NAME_MAPPINGS as REBAKE_DISP
from .backends.rebake_cpu import NODE_CLASS_MAPPINGS as REBAKE_CPU_MAPS, NODE_DISPLAY_NAME_MAPPINGS as REBAKE_CPU_DISP
from .backends.rebake_gpu import NODE_CLASS_MAPPINGS as REBAKE_GPU_MAPS, NODE_DISPLAY_NAME_MAPPINGS as REBAKE_GPU_DISP

NODE_CLASS_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS = {}

NODE_CLASS_MAPPINGS.update(TEXTURE_TO_GEOM_MAPS)
NODE_DISPLAY_NAME_MAPPINGS.update(TEXTURE_TO_GEOM_DISP)
NODE_CLASS_MAPPINGS.update(DEPTH_NORMALS_MAPS)
NODE_DISPLAY_NAME_MAPPINGS.update(DEPTH_NORMALS_DISP)
NODE_CLASS_MAPPINGS.update(NORM_SURF_MAPS)
NODE_DISPLAY_NAME_MAPPINGS.update(NORM_SURF_DISP)
NODE_CLASS_MAPPINGS.update(REBAKE_MAPS)
NODE_DISPLAY_NAME_MAPPINGS.update(REBAKE_DISP)
NODE_CLASS_MAPPINGS.update(REBAKE_CPU_MAPS)
NODE_DISPLAY_NAME_MAPPINGS.update(REBAKE_CPU_DISP)
NODE_CLASS_MAPPINGS.update(REBAKE_GPU_MAPS)
NODE_DISPLAY_NAME_MAPPINGS.update(REBAKE_GPU_DISP)

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']
