# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2025 ComfyUI-GeometryPack Contributors

"""
Texture remeshing nodes (main dependencies only - no Blender)
"""

from .texture_to_geometry import NODE_CLASS_MAPPINGS as TEXTURE_TO_GEOM_MAPS, NODE_DISPLAY_NAME_MAPPINGS as TEXTURE_TO_GEOM_DISP
from .depth_normals_to_mesh import NODE_CLASS_MAPPINGS as DEPTH_NORMALS_MAPS, NODE_DISPLAY_NAME_MAPPINGS as DEPTH_NORMALS_DISP
from .backends.depth_normals_to_mesh_poisson import NODE_CLASS_MAPPINGS as DN2M_POISSON_MAPS, NODE_DISPLAY_NAME_MAPPINGS as DN2M_POISSON_DISP
from .backends.depth_normals_to_mesh_ball_pivoting import NODE_CLASS_MAPPINGS as DN2M_BP_MAPS, NODE_DISPLAY_NAME_MAPPINGS as DN2M_BP_DISP
from .normals_to_mesh import NODE_CLASS_MAPPINGS as NORM_SURF_MAPS, NODE_DISPLAY_NAME_MAPPINGS as NORM_SURF_DISP
from .backends.normals_to_mesh_poisson_cpu import NODE_CLASS_MAPPINGS as N2M_CPU_MAPS, NODE_DISPLAY_NAME_MAPPINGS as N2M_CPU_DISP
# poisson_gpu backend disabled for now (code kept; also commented in normals_to_mesh.py):
# from .backends.normals_to_mesh_poisson_gpu import NODE_CLASS_MAPPINGS as N2M_GPU_MAPS, NODE_DISPLAY_NAME_MAPPINGS as N2M_GPU_DISP
from .backends.normals_to_mesh_frankot_chellappa import NODE_CLASS_MAPPINGS as N2M_FC_MAPS, NODE_DISPLAY_NAME_MAPPINGS as N2M_FC_DISP
from .rebake_texture import NODE_CLASS_MAPPINGS as REBAKE_MAPS, NODE_DISPLAY_NAME_MAPPINGS as REBAKE_DISP
from .backends.rebake_cpu import NODE_CLASS_MAPPINGS as REBAKE_CPU_MAPS, NODE_DISPLAY_NAME_MAPPINGS as REBAKE_CPU_DISP
from .backends.rebake_gpu import NODE_CLASS_MAPPINGS as REBAKE_GPU_MAPS, NODE_DISPLAY_NAME_MAPPINGS as REBAKE_GPU_DISP
from .backends.texture_to_geometry_grid import NODE_CLASS_MAPPINGS as T2G_GRID_MAPS, NODE_DISPLAY_NAME_MAPPINGS as T2G_GRID_DISP
from .backends.texture_to_geometry_poisson_pymeshlab import NODE_CLASS_MAPPINGS as T2G_PML_MAPS, NODE_DISPLAY_NAME_MAPPINGS as T2G_PML_DISP
from .backends.texture_to_geometry_delaunay2d import NODE_CLASS_MAPPINGS as T2G_DEL_MAPS, NODE_DISPLAY_NAME_MAPPINGS as T2G_DEL_DISP

NODE_CLASS_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS = {}

NODE_CLASS_MAPPINGS.update(TEXTURE_TO_GEOM_MAPS)
NODE_DISPLAY_NAME_MAPPINGS.update(TEXTURE_TO_GEOM_DISP)
NODE_CLASS_MAPPINGS.update(DEPTH_NORMALS_MAPS)
NODE_DISPLAY_NAME_MAPPINGS.update(DEPTH_NORMALS_DISP)
NODE_CLASS_MAPPINGS.update(DN2M_POISSON_MAPS)
NODE_DISPLAY_NAME_MAPPINGS.update(DN2M_POISSON_DISP)
NODE_CLASS_MAPPINGS.update(DN2M_BP_MAPS)
NODE_DISPLAY_NAME_MAPPINGS.update(DN2M_BP_DISP)
NODE_CLASS_MAPPINGS.update(NORM_SURF_MAPS)
NODE_DISPLAY_NAME_MAPPINGS.update(NORM_SURF_DISP)
NODE_CLASS_MAPPINGS.update(N2M_CPU_MAPS)
NODE_DISPLAY_NAME_MAPPINGS.update(N2M_CPU_DISP)
# NODE_CLASS_MAPPINGS.update(N2M_GPU_MAPS)
# NODE_DISPLAY_NAME_MAPPINGS.update(N2M_GPU_DISP)
NODE_CLASS_MAPPINGS.update(N2M_FC_MAPS)
NODE_DISPLAY_NAME_MAPPINGS.update(N2M_FC_DISP)
NODE_CLASS_MAPPINGS.update(REBAKE_MAPS)
NODE_DISPLAY_NAME_MAPPINGS.update(REBAKE_DISP)
NODE_CLASS_MAPPINGS.update(REBAKE_CPU_MAPS)
NODE_DISPLAY_NAME_MAPPINGS.update(REBAKE_CPU_DISP)
NODE_CLASS_MAPPINGS.update(REBAKE_GPU_MAPS)
NODE_DISPLAY_NAME_MAPPINGS.update(REBAKE_GPU_DISP)
NODE_CLASS_MAPPINGS.update(T2G_GRID_MAPS)
NODE_DISPLAY_NAME_MAPPINGS.update(T2G_GRID_DISP)
NODE_CLASS_MAPPINGS.update(T2G_PML_MAPS)
NODE_DISPLAY_NAME_MAPPINGS.update(T2G_PML_DISP)
NODE_CLASS_MAPPINGS.update(T2G_DEL_MAPS)
NODE_DISPLAY_NAME_MAPPINGS.update(T2G_DEL_DISP)

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']
