# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2025 ComfyUI-GeometryPack Contributors

"""Analysis module - mesh information and quality metrics."""

from .mesh_info import NODE_CLASS_MAPPINGS as MESH_INFO_MAPPINGS
from .mesh_info import NODE_DISPLAY_NAME_MAPPINGS as MESH_INFO_DISPLAY
from .mesh_quality import NODE_CLASS_MAPPINGS as MESH_QUALITY_MAPPINGS
from .mesh_quality import NODE_DISPLAY_NAME_MAPPINGS as MESH_QUALITY_DISPLAY
from .connected_components import NODE_CLASS_MAPPINGS as CONNECTED_COMPONENTS_MAPPINGS
from .connected_components import NODE_DISPLAY_NAME_MAPPINGS as CONNECTED_COMPONENTS_DISPLAY
from .open_edges import NODE_CLASS_MAPPINGS as OPEN_EDGES_MAPPINGS
from .open_edges import NODE_DISPLAY_NAME_MAPPINGS as OPEN_EDGES_DISPLAY
from .degenerate_faces import NODE_CLASS_MAPPINGS as DEGENERATE_FACES_MAPPINGS
from .degenerate_faces import NODE_DISPLAY_NAME_MAPPINGS as DEGENERATE_FACES_DISPLAY
from .bad_winding_faces import NODE_CLASS_MAPPINGS as BAD_WINDING_MAPPINGS
from .bad_winding_faces import NODE_DISPLAY_NAME_MAPPINGS as BAD_WINDING_DISPLAY
from .scramble_field import NODE_CLASS_MAPPINGS as SCRAMBLE_FIELD_MAPPINGS
from .scramble_field import NODE_DISPLAY_NAME_MAPPINGS as SCRAMBLE_FIELD_DISPLAY
from .extract_largest_component import NODE_CLASS_MAPPINGS as EXTRACT_LARGEST_MAPPINGS
from .extract_largest_component import NODE_DISPLAY_NAME_MAPPINGS as EXTRACT_LARGEST_DISPLAY
from .ultimate_mesh_inspection import NODE_CLASS_MAPPINGS as ULTIMATE_INSPECT_MAPPINGS
from .ultimate_mesh_inspection import NODE_DISPLAY_NAME_MAPPINGS as ULTIMATE_INSPECT_DISPLAY
from .compute_curvature import NODE_CLASS_MAPPINGS as COMPUTE_CURVATURE_MAPPINGS
from .compute_curvature import NODE_DISPLAY_NAME_MAPPINGS as COMPUTE_CURVATURE_DISPLAY
from .compute_fillet_field import NODE_CLASS_MAPPINGS as FILLET_FIELD_MAPPINGS
from .compute_fillet_field import NODE_DISPLAY_NAME_MAPPINGS as FILLET_FIELD_DISPLAY
from .segment_by_curvature import NODE_CLASS_MAPPINGS as SEGMENT_CURVATURE_MAPPINGS
from .segment_by_curvature import NODE_DISPLAY_NAME_MAPPINGS as SEGMENT_CURVATURE_DISPLAY
from .segment_patches import NODE_CLASS_MAPPINGS as SEGMENT_PATCHES_MAPPINGS
from .segment_patches import NODE_DISPLAY_NAME_MAPPINGS as SEGMENT_PATCHES_DISPLAY
from .region_growing import NODE_CLASS_MAPPINGS as REGION_GROWING_MAPPINGS
from .region_growing import NODE_DISPLAY_NAME_MAPPINGS as REGION_GROWING_DISPLAY

# Combine all mappings
NODE_CLASS_MAPPINGS = {
    **MESH_INFO_MAPPINGS,
    **MESH_QUALITY_MAPPINGS,
    **CONNECTED_COMPONENTS_MAPPINGS,
    **OPEN_EDGES_MAPPINGS,
    **DEGENERATE_FACES_MAPPINGS,
    **BAD_WINDING_MAPPINGS,
    **SCRAMBLE_FIELD_MAPPINGS,
    **EXTRACT_LARGEST_MAPPINGS,
    **ULTIMATE_INSPECT_MAPPINGS,
    **COMPUTE_CURVATURE_MAPPINGS,
    **FILLET_FIELD_MAPPINGS,
    **SEGMENT_CURVATURE_MAPPINGS,
    **SEGMENT_PATCHES_MAPPINGS,
    **REGION_GROWING_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **MESH_INFO_DISPLAY,
    **MESH_QUALITY_DISPLAY,
    **CONNECTED_COMPONENTS_DISPLAY,
    **OPEN_EDGES_DISPLAY,
    **DEGENERATE_FACES_DISPLAY,
    **BAD_WINDING_DISPLAY,
    **SCRAMBLE_FIELD_DISPLAY,
    **EXTRACT_LARGEST_DISPLAY,
    **ULTIMATE_INSPECT_DISPLAY,
    **COMPUTE_CURVATURE_DISPLAY,
    **FILLET_FIELD_DISPLAY,
    **SEGMENT_CURVATURE_DISPLAY,
    **SEGMENT_PATCHES_DISPLAY,
    **REGION_GROWING_DISPLAY,
}

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']
